### ISSUE TITLE
Not published to npm yet

### ISSUE THREAD

**Issue by eliwilliamson** [kristofferahl/roots-sass#1]
Can you please publish this so i can use the npm install script?

**Comment by kristofferahl** [comment]
@eliwilliamson Hi,
The number one reason is that I simply haven't worked with roots for a while now. Also,
when I posted about my module in the gitter.im chat room I got the following reply from @jenius:

"Very nice! is there any reason you don't just use sass with the extension?
its supported natively
you can just name the file .scss and use the compiler options in app.coffee"

So it seems I had missed that there was already support for sass built in...

You are most welcome to fork the repo and publish the module yourself!

**Comment by eliwilliamson** [comment]
Oh well - I must've missed that support as well. They ought to do a tutorial or have somewhere on the site/documentation that mentions this features persistence in v3.

**Comment by jescalan** [comment]
Hey there @eliwilliamson! If you have any questions or want some help with anything, I'd be happy to be of assistance. You can join us in the roots gitter channel, file an issue, or reach out to me personally if you'd like.

As far as the sass thing, we definitely do need to add better documentation on all the languages that can be used. Roots supports a huge number of languages, and our documentation as far as how exactly to implement each one is not as strong as it could be. Improving this is high on my list, but for now if you ask in the gitter channel you will quickly get an answer :grinning:
